FROM            eb-docker-re:base
MAINTAINER      d.sehyeon@gmail.com

ENV             BUILD_MODE      dev
ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

COPY            .   /srv/project

